fn reduce_shards(shard_dir:&Path,out_dir:&Path,null_iterations:usize,min_sources:usize)->Result<Value>{
 let mut rule_writer=BufWriter::new(File::create(out_dir.join("rules.jsonl"))?);let mut rule_count=0u64;let mut observed=HashMap::<String,Score>::new();let mut null_scores:HashMap<(String,usize),Score>=HashMap::new();
 for shard in 0..SHARDS{let path=shard_dir.join(format!("grammar-{shard:02}.tsv"));let mut train:HashMap<String,HashMap<String,OutcomeAgg>>=HashMap::new();
  {let reader=BufReader::new(File::open(&path)?);for line in reader.lines(){let line=line?;let parts:Vec<&str>=line.split('\t').collect();if parts.len()!=7{bail!("malformed grammar shard line in {}",path.display());}let iteration:i32=parts[0].parse()?;if iteration!=-1||parts[1]!="train"{continue;}let source=parts[2].to_string();let context=parts[4].to_string();let outcome=parts[5].to_string();let count:u64=parts[6].parse()?;let agg=train.entry(context).or_default().entry(outcome).or_default();agg.count+=count as u128;agg.sources.insert(source);}}
  let mut rules=HashMap::<String,Rule>::new();for(context,outcomes)in train{let mut context_sources=HashSet::new();for agg in outcomes.values(){context_sources.extend(agg.sources.iter().cloned());}if context_sources.len()<min_sources{continue;}let mut ranked:Vec<(String,usize,u128)>=outcomes.into_iter().map(|(outcome,agg)|(outcome,agg.sources.len(),agg.count)).collect();ranked.sort_by(|a,b|b.1.cmp(&a.1).then_with(||b.2.cmp(&a.2)).then_with(||a.0.cmp(&b.0)));let Some(best)=ranked.first()else{continue;};let rule=Rule{outcome:best.0.clone(),distinct_sources:best.1,total_count:best.2,context_sources:context_sources.len()};serde_json::to_writer(&mut rule_writer,&json!({"schema":"mark_sparse_rule_v1","context":context,"predictedOutcome":rule.outcome,"distinctSourceObjects":rule.distinct_sources,"contextSourceObjects":rule.context_sources,"supportCount":rule.total_count.to_string()}))?;rule_writer.write_all(b"\n")?;rule_count+=1;rules.insert(context,rule);}
  let reader=BufReader::new(File::open(&path)?);for line in reader.lines(){let line=line?;let parts:Vec<&str>=line.split('\t').collect();if parts.len()!=7{bail!("malformed grammar shard line in {}",path.display());}let iteration:i32=parts[0].parse()?;let lane=parts[1];if lane!="holdout"&&lane!="control"{continue;}let context=parts[4];let outcome=parts[5];let count:u64=parts[6].parse()?;let score=if iteration==-1{observed.entry(lane.to_string()).or_default()}else{if iteration<0||iteration as usize>=null_iterations{continue;}null_scores.entry((lane.to_string(),iteration as usize)).or_default()};score.examples+=count as u128;if let Some(rule)=rules.get(context){score.covered+=count as u128;if rule.outcome==outcome{score.correct+=count as u128;}}}
 }
 rule_writer.flush()?;let lane_summary=|lane:&str|{let obs=observed.get(lane).cloned().unwrap_or_default();let mut null_accuracy=Vec::new();let mut null_coverage=Vec::new();for i in 0..null_iterations{let s=null_scores.get(&(lane.to_string(),i)).cloned().unwrap_or_default();null_accuracy.push(ratio(s.correct,s.covered));null_coverage.push(ratio(s.covered,s.examples));}let mean_acc=mean(&null_accuracy);let mean_cov=mean(&null_coverage);json!({"examples":obs.examples.to_string(),"covered":obs.covered.to_string(),"correct":obs.correct.to_string(),"coverage":ratio(obs.covered,obs.examples),"accuracy":ratio(obs.correct,obs.covered),"nullMeanCoverage":mean_cov,"nullMeanAccuracy":mean_acc,"accuracyLift":ratio(obs.correct,obs.covered)-mean_acc,"nullIterations":null_iterations})};
 Ok(json!({"schema":"mark_sparse_transfer_evaluation_v1","rules":rule_count,"holdout":lane_summary("holdout"),"control":lane_summary("control"),"nullContract":"within each observation, arm tokens are deterministically permuted only among centers with identical center kind and degree; center inventory, degree sequence, arm-token inventory, lane, source and observation remain fixed"}))
}
fn ratio(n:u128,d:u128)->f64{if d==0{0.0}else{n as f64/d as f64}}
fn mean(values:&[f64])->f64{if values.is_empty(){0.0}else{values.iter().sum::<f64>()/values.len()as f64}}
fn parse_arg(args:&[String],name:&str,default:Option<&str>)->Result<String>{if let Some(pos)=args.iter().position(|a|a==name){return args.get(pos+1).cloned().ok_or_else(||anyhow!("missing value for {name}"));}default.map(str::to_owned).ok_or_else(||anyhow!("required argument {name}"))}
