fn main()->Result<()>{
 let args:Vec<String>=std::env::args().collect();if args.get(1).map(String::as_str)!=Some("compile"){bail!("usage: mark-sparse-compiler compile --input <blind.json> --out <dir> [--tile 512] [--overlap 32] [--null-iterations 16]");}
 let input_path=PathBuf::from(parse_arg(&args,"--input",None)?);let out_dir=PathBuf::from(parse_arg(&args,"--out",Some("artifacts/mark-v7-sparse"))?);let tile_size:u32=parse_arg(&args,"--tile",Some("512"))?.parse()?;let overlap:u32=parse_arg(&args,"--overlap",Some("32"))?.parse()?;let null_iterations:usize=parse_arg(&args,"--null-iterations",Some("16"))?.parse()?;let min_sources:usize=parse_arg(&args,"--min-sources",Some("3"))?.parse()?;if tile_size<64||overlap*2>=tile_size{bail!("tile must be >=64 and overlap must be less than half the tile size");}
 fs::create_dir_all(&out_dir)?;let bytes=fs::read(&input_path)?;let input:BlindInput=serde_json::from_slice(&bytes)?;if input.schema!="mark_observable_input_blind_v1"{bail!("unsupported input schema {}",input.schema);}if input.blind_input_sha256.len()!=64{bail!("blind input is missing its sealed SHA-256");}let input_blind_sha256=input.blind_input_sha256.clone();
 let source_by_id:HashMap<String,BlindSource>=input.sources.iter().cloned().map(|s|(s.source_group_id.clone(),s)).collect();let mut observations_by_source:HashMap<String,Vec<Observation>>=HashMap::new();for observation in input.observations.iter().cloned(){if !source_by_id.contains_key(&observation.source_group_id){bail!("unknown source {}",observation.source_group_id);}observations_by_source.entry(observation.source_group_id.clone()).or_default().push(observation);}for observations in observations_by_source.values_mut(){observations.sort_by(|a,b|a.id.cmp(&b.id));}
 let mut ledger=ChunkedLedger::create(&out_dir.join("events.jsonl"))?;let shard_dir=out_dir.join("grammar-shards");let mut shards=GrammarShards::create(&shard_dir)?;let mut stats=CompilerStats::default();let base_dir=input_path.parent().unwrap_or_else(||Path::new("."));let mut sources=input.sources.clone();sources.sort_by(|a,b|a.source_group_id.cmp(&b.source_group_id));
 for(source_index,source)in sources.iter().enumerate(){let capture=base_dir.join(&source.capture_path);let image=image::open(&capture).with_context(||format!("decode {}",capture.display()))?.to_luma8();let observations=observations_by_source.get(&source.source_group_id).map(Vec::as_slice).unwrap_or(&[]);for observation in observations{if observation.lane!=source.lane{bail!("lane mismatch for {}: source={} observation={}",observation.id,source.lane,observation.lane);}compile_observation(&image,observation,tile_size,overlap,null_iterations,&mut ledger,&mut shards,&mut stats)?;}stats.sources+=1;eprintln!("v7 sparse compile: {}/{} sources, {} observations, {} centers",source_index+1,sources.len(),stats.observations,stats.centers);drop(image);}
 shards.flush()?;let(ledger_lines,chunk_hashes,merkle_root)=ledger.finish()?;let evaluation=reduce_shards(&shard_dir,&out_dir,null_iterations,min_sources)?;
 let custody=json!({"schema":"mark_sparse_ledger_custody_v1","sourceBlindInputSha256":input_blind_sha256.clone(),"ledger":"events.jsonl","ledgerLines":ledger_lines,"chunkLines":LEDGER_CHUNK_LINES,"chunkHashes":chunk_hashes.clone(),"merkleRoot":merkle_root.clone(),"contract":{"appendOnlyEventLedger":true,"semanticLabelsAvailable":false,"wholeWorldGraphMaterialized":false,"wholeWorldJsonMaterialized":false,"grammarPairsMaterialized":false,"sourcePixelsRetainedInCustodyNotLedger":true}});fs::write(out_dir.join("custody.json"),serde_json::to_vec_pretty(&custody)?)?;fs::write(out_dir.join("evaluation.json"),serde_json::to_vec_pretty(&evaluation)?)?;
 let summary=json!({"schema":"mark_sparse_compiler_summary_v1","sourceBlindInputSha256":input_blind_sha256.clone(),"sources":stats.sources,"observations":stats.observations,"tiles":stats.tiles,"centers":stats.centers,"events":stats.events,"grammarRows":stats.grammar_rows,"observedPairWeight":stats.observed_pair_weight.to_string(),"unresolvedArms":stats.unresolved_arms,"tileSize":tile_size,"overlap":overlap,"grammarShards":SHARDS,"nullIterations":null_iterations,"ledgerMerkleRoot":merkle_root.clone(),"evaluation":evaluation});fs::write(out_dir.join("summary.json"),serde_json::to_vec_pretty(&summary)?)?;println!("{}",serde_json::to_string_pretty(&summary)?);Ok(())
}
